import Script from "next/script";
import Link from "next/link";

export const metadata = {
  title: "Outlook Password Not Accepted? Fix Guide (2026)",
  description: "Outlook keeps asking for password or says password incorrect? Fix authentication errors, app passwords, 2FA issues, and credential problems step by step.",
  alternates: { canonical: "/outlook-password-not-accepted" },
  openGraph: { title: "Outlook Password Not Accepted — Fix Guide", description: "Fix Outlook password rejection.", type: "article", url: "https://techsupport4.com/outlook-password-not-accepted" },
  twitter: { card: "summary_large_image", title: "Outlook Password Fix | TechSupport4", description: "Outlook won't accept password — fix guide." },
};

const faqs = [
  { q: "Why does Outlook keep asking for my password?", a: "Common causes: (1) Cached credential expired in Windows Credential Manager, (2) Two-factor authentication enabled but Outlook needs an app password instead, (3) OAuth token expired — need to re-authorize, (4) Outlook profile corrupted, (5) Microsoft disabled basic authentication (legacy auth deprecated in 2024), (6) Password was changed on another device but Outlook still has old one, (7) Antivirus interfering with Outlook authentication." },
  { q: "What is an app password and when do I need one?", a: "An app password is a 16-character password generated by your email provider that replaces your regular password for apps that don't support modern authentication. You need one when: (1) Using 2FA/two-step verification, (2) Using classic Outlook (not New Outlook) with Gmail, Yahoo, or iCloud, (3) Your account requires modern auth but Outlook isn't supporting it properly." },
  { q: "How do I generate a Microsoft app password?", a: "Go to account.microsoft.com → Security → Advanced security options → App passwords → Create a new app password. Copy the generated password → use it in Outlook instead of your regular password. Note: App passwords only work if your admin hasn't disabled them." },
  { q: "Outlook works in browser but desktop app won't accept password", a: "This usually means the desktop app has stale credentials. Fix: (1) Close Outlook, (2) Open Credential Manager → Windows Credentials → remove all Microsoft Office and Outlook entries, (3) Open Outlook — it will prompt for fresh login, (4) If still failing, try: File → Account Settings → Repair account, (5) For Microsoft 365, ensure Modern Authentication is enabled in registry." },
  { q: "Gmail password not accepted in Outlook — how to fix?", a: "Google disabled 'less secure app access.' You need to: (1) Enable 2-Step Verification on your Google account, (2) Generate an App Password: Google Account → Security → App passwords → select 'Mail' and 'Windows Computer' → generate, (3) Use this 16-character app password in Outlook instead of your Gmail password." },
];

export default function OutlookPasswordNotAccepted() {
  return (
    <>
      <Script id="article-schema" type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify({ "@context": "https://schema.org", "@type": "Article", headline: "Outlook Password Not Accepted — Fix Guide", description: "Fix Outlook password rejection.", author: { "@type": "Organization", name: "TechSupport4" }, publisher: { "@type": "Organization", name: "TechSupport4", url: "https://techsupport4.com" }, datePublished: "2026-02-26", dateModified: "2026-02-28" }) }} />
      <Script id="faq-schema" type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify({ "@context": "https://schema.org", "@type": "FAQPage", mainEntity: faqs.map((f) => ({ "@type": "Question", name: f.q, acceptedAnswer: { "@type": "Answer", text: f.a } })) }) }} />

      <main className="bg-slate-50 dark:bg-slate-900 min-h-screen">
        <section className="bg-gradient-to-br from-slate-900 via-blue-900 to-slate-800 text-white py-16 md:py-20 px-6">
          <div className="max-w-4xl mx-auto">
            <nav className="flex items-center gap-2 text-blue-300 text-sm mb-6 flex-wrap">
              <Link href="/" className="hover:text-white transition">Home</Link>
              <svg className="w-3 h-3" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 5l7 7-7 7" /></svg>
              <Link href="/outlook-not-working" className="hover:text-white transition">Outlook Not Working</Link>
              <svg className="w-3 h-3" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 5l7 7-7 7" /></svg>
              <span className="text-white">Password Not Accepted</span>
            </nav>
            <span className="inline-block bg-red-500/20 text-red-300 text-xs font-semibold px-3 py-1 rounded-full mb-4 border border-red-500/30">Authentication Issue</span>
            <h1 className="text-3xl md:text-4xl lg:text-5xl font-heading font-bold leading-tight">Outlook Password Not Accepted? Fix Guide</h1>
            <p className="mt-4 text-blue-200 text-lg max-w-2xl">Outlook keeps asking for your password or says it&apos;s wrong? Fix credential errors, app password requirements, 2FA issues, and authentication loops.</p>
            <div className="flex items-center gap-4 mt-6 text-sm text-blue-300"><span>Updated: Feb 2026</span><span className="w-1 h-1 rounded-full bg-blue-400" /><span>11 min read</span></div>
          </div>
        </section>

        <article className="max-w-4xl mx-auto px-6 py-14">
          <p className="text-slate-600 dark:text-slate-300 text-lg leading-relaxed mb-6">You type your correct password into Outlook, but it keeps rejecting it — or Outlook keeps popping up the password dialog in an endless loop. This problem has become extremely common since Microsoft deprecated basic authentication. The fix depends on your email provider.</p>

          <h2 className="text-2xl font-bold text-slate-800 dark:text-white mt-10 mb-4">Fix 1: Clear Cached Credentials</h2>
          <p className="text-slate-600 dark:text-slate-300 leading-relaxed mb-4">Old saved passwords are the #1 cause of password loops:</p>
          <ol className="list-decimal pl-6 text-slate-600 dark:text-slate-300 space-y-2 mb-8">
            <li><strong>Close Outlook completely</strong></li>
            <li>Open <strong>Control Panel → Credential Manager</strong></li>
            <li>Click <strong>Windows Credentials</strong></li>
            <li>Look for entries containing: <strong>outlook, office, microsoftoffice16, mso</strong></li>
            <li><strong>Remove all</strong> of these entries (click the dropdown → Remove)</li>
            <li>Open Outlook — it will ask for your password fresh</li>
            <li>Enter your <strong>current correct password</strong></li>
          </ol>

          <h2 className="text-2xl font-bold text-slate-800 dark:text-white mt-10 mb-4">Fix 2: Use App Password (For 2FA Accounts)</h2>
          <p className="text-slate-600 dark:text-slate-300 leading-relaxed mb-4">If you have two-factor authentication enabled, your regular password won&apos;t work. Generate an app password:</p>
          <h3 className="text-xl font-semibold text-slate-700 dark:text-slate-200 mt-6 mb-3">For Microsoft/Outlook.com/Hotmail:</h3>
          <ol className="list-decimal pl-6 text-slate-600 dark:text-slate-300 space-y-2 mb-4">
            <li>Go to <strong>account.microsoft.com</strong> → sign in</li>
            <li><strong>Security → Advanced security options</strong></li>
            <li>Scroll to <strong>App passwords → Create a new app password</strong></li>
            <li>Copy the 16-character password</li>
            <li>Use this in Outlook instead of your regular password</li>
          </ol>
          <h3 className="text-xl font-semibold text-slate-700 dark:text-slate-200 mt-6 mb-3">For Gmail:</h3>
          <ol className="list-decimal pl-6 text-slate-600 dark:text-slate-300 space-y-2 mb-4">
            <li>Go to <strong>myaccount.google.com → Security</strong></li>
            <li>Enable <strong>2-Step Verification</strong> (required first)</li>
            <li>Go to <strong>App passwords</strong></li>
            <li>Select App: <strong>Mail</strong>, Device: <strong>Windows Computer</strong></li>
            <li>Click <strong>Generate</strong> → copy the 16-character password</li>
            <li>Use this app password in Outlook</li>
          </ol>
          <h3 className="text-xl font-semibold text-slate-700 dark:text-slate-200 mt-6 mb-3">For Yahoo:</h3>
          <ol className="list-decimal pl-6 text-slate-600 dark:text-slate-300 space-y-2 mb-8">
            <li>Go to <strong>login.yahoo.com → Account Security</strong></li>
            <li>Click <strong>Generate app password</strong></li>
            <li>Select <strong>Outlook Desktop</strong></li>
            <li>Use the generated password in Outlook</li>
          </ol>

          <h2 className="text-2xl font-bold text-slate-800 dark:text-white mt-10 mb-4">Fix 3: Enable Modern Authentication</h2>
          <p className="text-slate-600 dark:text-slate-300 leading-relaxed mb-4">Microsoft 365 accounts require modern authentication (OAuth2). Ensure it&apos;s enabled:</p>
          <ol className="list-decimal pl-6 text-slate-600 dark:text-slate-300 space-y-2 mb-4">
            <li>Press <strong>Win + R</strong> → type <strong>regedit</strong> → Enter</li>
            <li>Navigate to: <code className="bg-slate-200 dark:bg-slate-700 px-1 rounded">HKEY_CURRENT_USER\Software\Microsoft\Office\16.0\Common\Identity</code></li>
            <li>Create/set DWORD <strong>EnableADAL</strong> = <strong>1</strong></li>
            <li>Create/set DWORD <strong>Version</strong> = <strong>1</strong></li>
            <li>Restart Outlook</li>
          </ol>
          <p className="text-slate-600 dark:text-slate-300 leading-relaxed mb-8">This forces Outlook to use modern authentication, which opens a browser-based login window instead of the old password dialog.</p>

          <h2 className="text-2xl font-bold text-slate-800 dark:text-white mt-10 mb-4">Fix 4: Repair Outlook Account</h2>
          <ol className="list-decimal pl-6 text-slate-600 dark:text-slate-300 space-y-2 mb-8">
            <li>Open Outlook → <strong>File → Account Settings → Account Settings</strong></li>
            <li>Select the problematic account</li>
            <li>Click <strong>Repair</strong></li>
            <li>Follow the wizard — it will re-verify server settings and authentication</li>
            <li>If prompted for password, enter current password or app password</li>
          </ol>

          <h2 className="text-2xl font-bold text-slate-800 dark:text-white mt-10 mb-4">Fix 5: Reset Microsoft 365 Password</h2>
          <p className="text-slate-600 dark:text-slate-300 leading-relaxed mb-8">If you genuinely forgot or your password was changed by an admin: Go to <strong>account.live.com/password/reset</strong> (personal) or contact your IT admin (work account). After resetting online, clear Outlook credentials (Fix 1) and enter the new password.</p>

          <h2 className="text-2xl font-bold text-slate-800 dark:text-white mt-10 mb-4">Fix 6: Remove and Re-add Account</h2>
          <ol className="list-decimal pl-6 text-slate-600 dark:text-slate-300 space-y-2 mb-8">
            <li>Open Outlook → <strong>File → Account Settings → Account Settings</strong></li>
            <li>Select the account → click <strong>Remove</strong></li>
            <li>Close Outlook → clear credentials from Credential Manager (Fix 1)</li>
            <li>Reopen Outlook → <strong>File → Add Account</strong></li>
            <li>Enter your email address → follow the setup wizard</li>
            <li>Microsoft 365 accounts should open a browser-based login</li>
          </ol>

          <h2 className="text-2xl font-bold text-slate-800 dark:text-white mt-10 mb-4">Fix 7: Create New Outlook Profile</h2>
          <p className="text-slate-600 dark:text-slate-300 leading-relaxed mb-4">Last resort for persistent password loops:</p>
          <ol className="list-decimal pl-6 text-slate-600 dark:text-slate-300 space-y-2 mb-8">
            <li>Close Outlook</li>
            <li>Open <strong>Control Panel → Mail → Show Profiles</strong></li>
            <li>Click <strong>Add</strong> → name it &quot;Fresh&quot;</li>
            <li>Set up your email account in this new profile</li>
            <li>Set as <strong>&quot;Always use this profile&quot;</strong></li>
            <li>This gives you a clean Outlook configuration with no stale credential.</li>
          </ol>

          <section className="mt-14 border-t border-slate-200 dark:border-slate-700 pt-10">
            <h2 className="text-2xl font-bold text-slate-800 dark:text-white mb-6">Frequently Asked Questions</h2>
            <div className="space-y-6">{faqs.map((faq, i) => (<div key={i} className="bg-white dark:bg-slate-800 rounded-xl p-5 border border-slate-200 dark:border-slate-700"><h3 className="font-semibold text-slate-800 dark:text-white">{faq.q}</h3><p className="mt-2 text-slate-600 dark:text-slate-300 text-sm leading-relaxed">{faq.a}</p></div>))}</div>
          </section>

          <div className="mt-12 bg-gradient-to-br from-blue-700 to-blue-900 text-white rounded-2xl p-8 md:p-10 text-center">
            <h3 className="text-2xl font-heading font-bold">Outlook Password Still Failing?</h3>
            <p className="mt-2 text-blue-200 max-w-lg mx-auto">Our technicians can fix Outlook authentication issues and account configuration remotely.</p>
            <div className="flex flex-col sm:flex-row gap-4 justify-center mt-6">
              <Link href="/contact" className="inline-flex items-center justify-center bg-white text-blue-700 px-8 py-3 rounded-xl font-semibold hover:bg-blue-50 transition">Start Secure Session</Link>
              <a href={`tel:${process.env.NEXT_PUBLIC_PHONE_USA}`} className="inline-flex items-center justify-center border-2 border-white/30 text-white px-8 py-3 rounded-xl font-semibold hover:bg-white/10 transition">Call {process.env.NEXT_PUBLIC_PHONE_DISPLAY}</a>
            </div>
          </div>

          <div className="mt-12">
            <h3 className="text-lg font-heading font-bold text-slate-800 dark:text-white mb-4">Related Guides</h3>
            <div className="grid sm:grid-cols-2 gap-4">
              {[
                { href: "/outlook-not-sending-emails-windows-11", title: "Outlook Not Sending", desc: "Fix Outlook send failures." },
                { href: "/outlook-not-working", title: "Outlook Not Working?", desc: "General Outlook fix guide." },
                { href: "/gmail-login-problem-fix", title: "Gmail Login Problem", desc: "Fix Gmail sign-in issues." },
                { href: "/email-not-working", title: "Email Not Working?", desc: "Universal email fix guide." },
              ].map((g) => (<Link key={g.href} href={g.href} className="bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 rounded-xl p-4 hover:shadow-md transition group"><p className="font-semibold text-blue-700 dark:text-blue-400 group-hover:text-blue-600">{g.title}</p><p className="text-slate-500 dark:text-slate-400 text-sm mt-1">{g.desc}</p></Link>))}
            </div>
          </div>
        </article>
      </main>
    </>
  );
}
